### ISSUE TITLE
Laravel 8 - Filesystem::database does not exist

### ISSUE THREAD

**Issue by DubStepMad** [joedixon/laravel-translation#129]
**Describe the bug**
When running the command  `php artisan translation:sync-translations` on a Ubuntu 18.04.5 LTS I am met with the following error `Method Illuminate\Filesystem\Filesystem::database does not exist.`.

This command works on my local system (Windows 10) but once moved to the web server I get the error.

**To Reproduce**
1. Update to Laravel 8 
2. Run `php artisan translation:sync-translations`

**Expected behavior**
For the command to execute as intended.

**Stacktrace**

```
[2020-09-27 23:51:08] local.ERROR: Method Illuminate\Filesystem\Filesystem::database does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Filesystem\\Filesystem::database does not exist. at /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:103)
[stacktrace]
#0 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Filesystem\\Filesystem->__call()
#1 /var/www/vhosts/asphalt.events/httpdocs/vendor/symfony/console/Helper/QuestionHelper.php(252): Illuminate\\Support\\Facades\\Facade::__callStatic()
#2 /var/www/vhosts/asphalt.events/httpdocs/vendor/symfony/console/Helper/QuestionHelper.php(141): Symfony\\Component\\Console\\Helper\\QuestionHelper->autocomplete()
#3 /var/www/vhosts/asphalt.events/httpdocs/vendor/symfony/console/Helper/QuestionHelper.php(64): Symfony\\Component\\Console\\Helper\\QuestionHelper->doAsk()
#4 /var/www/vhosts/asphalt.events/httpdocs/vendor/symfony/console/Style/SymfonyStyle.php(355): Symfony\\Component\\Console\\Helper\\QuestionHelper->ask()
#5 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Concerns/InteractsWithIO.php(176): Symfony\\Component\\Console\\Style\\SymfonyStyle->askQuestion()
#6 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Concerns/InteractsWithIO.php(157): Illuminate\\Console\\Command->askWithCompletion()
#7 /var/www/vhosts/asphalt.events/httpdocs/vendor/joedixon/laravel-translation/src/Console/Commands/SynchroniseTranslationsCommand.php(87): Illuminate\\Console\\Command->anticipate()
#8 [internal function]: JoeDixon\\Translation\\Console\\Commands\\SynchroniseTranslationsCommand->handle()
#9 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#10 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#14 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#15 /var/www/vhosts/asphalt.events/httpdocs/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#16 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#17 /var/www/vhosts/asphalt.events/httpdocs/vendor/symfony/console/Application.php(916): Illuminate\\Console\\Command->run()
#18 /var/www/vhosts/asphalt.events/httpdocs/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#19 /var/www/vhosts/asphalt.events/httpdocs/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#20 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#21 /var/www/vhosts/asphalt.events/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#22 /var/www/vhosts/asphalt.events/httpdocs/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#23 {main}
"} 
```

**Comment by DubStepMad** [comment]
I was able to debug this issue.

It seems that when upgrading it doesn't like the terminal commands being inputted manually so you have to enter the command like: `php artisan translation:sync-translations {from [file or database]}  {to [file or database]}`

Which I had to do `php artisan translation:sync-translations file database`
